# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-06 23:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maxpain', '0002_optionchain_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='optionchain',
            name='change_open_interest',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='optionchain',
            name='created_on',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='optionchain',
            name='last_traded_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='optionchain',
            name='open_interest',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='optionchain',
            name='spot_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='optionchain',
            name='strike_price',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='optionchain',
            name='volatility',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='optionchain',
            name='stock_symbol',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
